<?php
error_reporting(E_PARSE);
if($_GET['_SESSION'] != '' || $_POST['_SESSION'] != '' || $_COOKIE['_SESSION'] != '') { exit; }
session_start();

function create_table($tbl_name){
	if(!table_exists($tbl_name)){
		$create_tables['blog_category'] = 'CREATE TABLE blog_category ( prikey int(11) NOT NULL auto_increment primary key, category_name varchar(255) default NULL)';
		$create_tables['blog_comments'] = 'CREATE TABLE blog_comments ( prikey int(11) NOT NULL auto_increment primary key, blog_key int(50) default NULL, name varchar(255) default NULL, email blob, comments blob, comment_date int(10) unsigned default NULL, status varchar(255) default NULL, ip_address varchar(255) default NULL, micro varchar(255) default NULL)';
		$create_tables['blog_content'] = 'CREATE TABLE blog_content ( prikey int(11) NOT NULL auto_increment primary key, blog_category int(11) default NULL, blog_title varchar(255) default NULL, blog_data blob, blog_date date default NULL, blog_tags blob, blog_author int(50) default NULL, timestamp varchar(50) default NULL, live varchar(255) default NULL, allow_comments varchar(255) default NULL)';
		$create_tables['calendar_category'] = 'CREATE TABLE calendar_category ( PRIKEY int(11) NOT NULL auto_increment primary key, Category_Name char(255) default NULL)';
		$create_tables['calendar_display'] = 'CREATE TABLE calendar_display ( PRIKEY int(11) NOT NULL auto_increment primary key, TEXT_COLOR varchar(7) default NULL, BACKGROUND_COLOR varchar(7) default NULL, ALLOW_PERSONAL_CALENDARS char(1) default NULL, DISPLAY_STYLE char(1) default NULL, ALLOW_PUBLIC_SUBMISSIONS char(1) default NULL, EMAIL_CONFIRMATION varchar(255) default NULL, FUTURE1 blob, FUTURE2 blob)';
		$create_tables['calendar_events'] = 'CREATE TABLE calendar_events ( PRIKEY int(11) NOT NULL auto_increment primary key, EVENT_DATE date default NULL, EVENT_KEYWORDS varchar(255) default NULL, EVENT_START time default NULL, EVENT_END time default NULL, EVENT_TITLE varchar(255) default NULL, EVENT_DETAILS blob, EVENT_CATEGORY varchar(50) default NULL, EVENT_DETAILPAGE varchar(50) default NULL, EVENT_EMAILNOTIFY varchar(255) default NULL, EVENT_SECURITYCODE varchar(255) default NULL, RECUR_MASTER varchar(255) default NULL, RECUR_LINK_KEYS varchar(255) default NULL, custom_start varchar(255) default NULL, custom_end varchar(255) default NULL)';
		$create_tables['campaign_manager'] = 'CREATE TABLE campaign_manager ( PRIKEY int(11) NOT NULL auto_increment primary key, STATUS varchar(15) default NULL, CAMPAIGN_NAME varchar(50) default NULL, TABLE_NAME varchar(50) default NULL, HTML_EMAIL_ADDR blob, TEXT_EMAIL_ADDR blob, FROM_ADDR varchar(255) default NULL, SUBJECT_LINE varchar(255) default NULL, HTML_CONTENT blob, IMAGE_ARRAY blob, WIZ_VARS blob, TEXT_CONTENT blob, NUM_HTML_CNT int(20) default NULL, NUM_TEXT_CNT int(20) default NULL, SEND_DATE date default NULL, CLICK_THRU_CNT int(50) default NULL, ARCHIVE_FLAG char(1) default NULL)';
		$create_tables['cart_authorize'] = 'CREATE TABLE cart_authorize ( AN_ACCTID varchar(255) default NULL, AN_ACCTKEY varchar(255) default NULL, AN_TMODE varchar(255) default NULL)';
		$create_tables['cart_category'] = 'CREATE TABLE cart_category ( keyfield int(11) NOT NULL auto_increment primary key, category varchar(255) default NULL, level int(255) NOT NULL default \'1\', subs blob, parent varchar(255) default NULL, product_count varchar(255) default NULL)';
		$create_tables['cart_comments'] = 'CREATE TABLE cart_comments ( PRIKEY int(11) NOT NULL auto_increment primary key, PROD_ID int(11) default NULL, COMMENT_TITLE varchar(255) default NULL, COMMENT blob, RATING varchar(255) default NULL, NAME varchar(255) default NULL, LOCATION varchar(255) default NULL, COMMENT_DATE datetime default NULL, STATUS varchar(255) default NULL, COMMENT_HTML blob, AUTH_KEY varchar(255) default NULL)';
		$create_tables['cart_coupons'] = 'CREATE TABLE cart_coupons ( prikey int(50) NOT NULL auto_increment primary key, code varchar(255) default NULL, products blob, categories varchar(255) default NULL, discount_type varchar(255) default NULL, discount_amount varchar(255) default NULL, cart_min varchar(255) default NULL, expiration varchar(60) default NULL, disc_per varchar(255) default NULL)';
		$create_tables['cart_customers'] = 'CREATE TABLE cart_customers ( PRIKEY int(11) NOT NULL auto_increment primary key, USERNAME varchar(100) default NULL, PASSWORD varchar(100) default NULL, BILLTO_FIRSTNAME varchar(100) default NULL, BILLTO_LASTNAME varchar(100) default NULL, BILLTO_COMPANY varchar(100) default NULL, BILLTO_ADDR1 varchar(100) default NULL, BILLTO_ADDR2 varchar(100) default NULL, BILLTO_CITY varchar(50) default NULL, BILLTO_STATE varchar(50) default NULL, BILLTO_COUNTRY varchar(75) default NULL, BILLTO_ZIPCODE varchar(20) default NULL, BILLTO_PHONE varchar(75) default NULL, BILLTO_EMAILADDR varchar(100) default NULL, SHIPTO_FIRSTNAME varchar(100) default NULL, SHIPTO_LASTNAME varchar(100) default NULL, SHIPTO_COMPANY varchar(100) default NULL, SHIPTO_ADDR1 varchar(100) default NULL, SHIPTO_ADDR2 varchar(100) default NULL, SHIPTO_CITY varchar(50) default NULL, SHIPTO_STATE varchar(50) default NULL, SHIPTO_COUNTRY varchar(75) default NULL, SHIPTO_ZIPCODE varchar(20) default NULL, SHIPTO_PHONE varchar(75) default NULL, FUTURE1 blob, FUTURE2 blob)';
		$create_tables['cart_dps'] = 'CREATE TABLE cart_dps ( DPS_USERNAME char(255) default NULL, DPS_PASSWORD char(255) default NULL, DPS_USER1 char(255) default NULL, DPS_USER2 char(255) default NULL)';
		$create_tables['cart_eway'] = 'CREATE TABLE cart_eway ( EWAY_ID varchar(255) default NULL, EWAY_USER1 varchar(255) default NULL, EWAY_USER2 varchar(255) default NULL, EWAY_USER3 varchar(255) default NULL, country_pref varchar(50) default NULL)';
		$create_tables['cart_innovgate'] = 'CREATE TABLE cart_innovgate ( IG_USER varchar(255) default NULL, IG_PASS varchar(255) default NULL, IG_TMODE varchar(5) default NULL, IG_LATER varchar(255) default NULL)';
		$create_tables['cart_invoice'] = 'CREATE TABLE cart_invoice ( ORDER_NUMBER int(11) NOT NULL auto_increment primary key, ORDER_DATE varchar(50) default NULL, ORDER_TIME varchar(25) default NULL, PAY_METHOD varchar(50) default NULL, CC_TYPE varchar(10) default NULL, CC_NUM varchar(100) default NULL, CC_AVS varchar(5) default NULL, CC_DATE varchar(25) default NULL, TRANSACTION_STATUS varchar(50) default NULL, TRANSACTION_ID varchar(75) default NULL, BILLTO_FIRSTNAME varchar(100) default NULL, BILLTO_LASTNAME varchar(100) default NULL, BILLTO_COMPANY varchar(100) default NULL, BILLTO_ADDR1 varchar(100) default NULL, BILLTO_ADDR2 varchar(100) default NULL, BILLTO_CITY varchar(50) default NULL, BILLTO_STATE varchar(50) default NULL, BILLTO_COUNTRY varchar(75) default NULL, BILLTO_ZIPCODE varchar(20) default NULL, BILLTO_PHONE varchar(75) default NULL, BILLTO_EMAILADDR varchar(100) default NULL, SHIPTO_FIRSTNAME varchar(100) default NULL, SHIPTO_LASTNAME varchar(100) default NULL, SHIPTO_COMPANY varchar(100) default NULL, SHIPTO_ADDR1 varchar(100) default NULL, SHIPTO_ADDR2 varchar(100) default NULL, SHIPTO_CITY varchar(50) default NULL, SHIPTO_STATE varchar(50) default NULL, SHIPTO_COUNTRY varchar(75) default NULL, SHIPTO_ZIPCODE varchar(20) default NULL, SHIPTO_PHONE varchar(75) default NULL, INVOICE_HTML blob, TOTAL_SALE varchar(50) default NULL, FUTURE1 blob, FUTURE2 blob)';
		$create_tables['cart_options'] = 'CREATE TABLE cart_options ( PAYMENT_CREDIT_CARDS varchar(30) default NULL, PAYMENT_CHECK_ONLY char(1) default NULL, PAYMENT_CATALOG_ONLY char(1) default NULL, PAYMENT_PROCESSING_TYPE varchar(255) default NULL, PAYMENT_CURRENCY_TYPE varchar(5) default NULL, PAYMENT_CURRENCY_SIGN varchar(12) default NULL, PAYMENT_VPARTNERID varchar(50) default NULL, PAYMENT_VLOGINID varchar(50) default NULL, PAYMENT_INCLUDE varchar(150) default NULL, PAYMENT_SSL varchar(255) default NULL, BIZ_PAYABLE varchar(100) default NULL, BIZ_ADDRESS_1 varchar(100) default NULL, BIZ_ADDRESS_2 varchar(100) default NULL, BIZ_CITY varchar(100) default NULL, BIZ_STATE varchar(100) default NULL, BIZ_POSTALCODE varchar(100) default NULL, BIZ_COUNTRY varchar(100) default NULL, BIZ_PHONE varchar(100) default NULL, BIZ_VERIFY_COMMENTS blob, BIZ_EMAIL_NOTICE blob, BIZ_INVOICE_HEADER blob, DISPLAY_HEADERBG varchar(7) default NULL, DISPLAY_HEADERTXT varchar(7) default NULL, DISPLAY_CARTBG varchar(7) default NULL, DISPLAY_CARTTXT varchar(7) default NULL, DISPLAY_WELCOME blob, DISPLAY_RESULTS char(2) default NULL, DISPLAY_RESULTSORT varchar(50) default NULL, DISPLAY_COLPLACEMENT char(1) default NULL, DISPLAY_SEARCH char(1) default NULL, DISPLAY_USERBUTTON varchar(55) default NULL, DISPLAY_ADDCARTBUTTON char(1) default NULL, DISPLAY_LOGINBUTTON char(1) default NULL, DISPLAY_CATEGORIES char(1) default NULL, DISPLAY_COMMENTS char(1) default NULL, DISPLAY_EMAILFRIEND char(1) default NULL, DISPLAY_REMEMBERME char(1) default NULL, DISPLAY_STATE varchar(25) default NULL, DISPLAY_ZIP varchar(150) default NULL, DISPLAY_REQUIRED blob, INVOICE_INCLUDE varchar(150) default NULL, LOCAL_COUNTRY blob, CHARGE_VAT varchar(4) default NULL, VAT_REG varchar(100) default NULL, CSS blob, GOTO_CHECKOUT varchar(20) default NULL)';
		$create_tables['cart_paypal'] = 'CREATE TABLE cart_paypal ( PAYPAL_EMAIL char(255) default NULL, PAYPAL_USER1 char(255) default NULL, PAYPAL_USER2 char(255) default NULL, PAYPAL_USER3 char(255) default NULL)';
		$create_tables['cart_paypoint'] = 'CREATE TABLE cart_paypoint ( SC_ACCTID varchar(255) default NULL, SC_SUBID varchar(255) default NULL, SC_PASSCODE varchar(255) default NULL, SC_TMODE varchar(255) default NULL)';
		$create_tables['cart_paypro'] = 'CREATE TABLE cart_paypro ( PAYPRO_ID char(255) default NULL, PAYPRO_TEST char(255) default NULL, PAYPRO_FUTURE1 char(255) default NULL)';
		$create_tables['cart_paystation'] = 'CREATE TABLE cart_paystation ( PAYSTATION_ID char(255) default NULL, PAYSTATION_FUTURE char(255) default NULL)';
		$create_tables['cart_products'] = 'CREATE TABLE cart_products ( PRIKEY int(11) NOT NULL auto_increment primary key, PROD_CATEGORY1 int(5) default NULL, PROD_CATEGORY2 int(5) default NULL, PROD_CATEGORY3 int(5) default NULL, PROD_SKU varchar(150) default NULL, PROD_CATNO varchar(150) default NULL, PROD_UNITPRICE varchar(10) default NULL, PROD_NAME varchar(255) default NULL, PROD_DESC blob, PROD_SHIPA varchar(50) default NULL, PROD_SHIPB varchar(50) default NULL, PROD_SHIPC varchar(50) default NULL, PROD_THUMBNAIL varchar(75) default NULL, PROD_FULLIMAGENAME varchar(75) default NULL, SUB_CAT1 varchar(150) default NULL, SUB_CAT2 varchar(150) default NULL, SUB_CAT3 varchar(150) default NULL, SUB_CAT4 varchar(150) default NULL, SUB_CAT5 varchar(150) default NULL, SUB_CAT6 varchar(150) default NULL, VARIANT_NAME1 varchar(150) default NULL, VARIANT_PRICE1 varchar(10) default NULL, VARIANT_NAME2 varchar(150) default NULL, VARIANT_PRICE2 varchar(10) default NULL, VARIANT_NAME3 varchar(150) default NULL, VARIANT_PRICE3 varchar(10) default NULL, VARIANT_NAME4 varchar(150) default NULL, VARIANT_PRICE4 varchar(10) default NULL, VARIANT_NAME5 varchar(150) default NULL, VARIANT_PRICE5 varchar(10) default NULL, VARIANT_NAME6 varchar(150) default NULL, VARIANT_PRICE6 varchar(10) default NULL, OPTION_DISPLAY char(1) default NULL, OPTION_CHARGETAX char(1) default NULL, OPTION_CHARGESHIPPING char(1) default NULL, OPTION_KEYWORDS text, OPTION_SECURITYCODE varchar(50) default NULL, OPTION_DETAILPAGE varchar(255) default NULL, OPTION_RECOMMENDSKU varchar(255) default NULL, OPTION_SHOWATEDIT char(1) default NULL, OPTION_FORMDATA varchar(75) default NULL, OPTION_FORMDISPLAY varchar(6) default NULL, OPTION_DOWNLOADFILE varchar(75) default NULL, OPTION_INVENTORY_NUM int(75) default NULL, SPECIAL_TAX varchar(15) default NULL, sub_cats blob, variant_names blob, variant_prices blob, num_variants varchar(20) default NULL, full_desc blob, other_images blob)';
		$create_tables['cart_shipping_opts'] = 'CREATE TABLE cart_shipping_opts ( SHIP_METHOD varchar(50) default NULL, ST_GTHAN1 varchar(50) default NULL, ST_LTHAN1 varchar(50) default NULL, ST_SHIP1 varchar(50) default NULL, ST_GTHAN2 varchar(50) default NULL, ST_LTHAN2 varchar(50) default NULL, ST_SHIP2 varchar(50) default NULL, ST_GTHAN3 varchar(50) default NULL, ST_LTHAN3 varchar(50) default NULL, ST_SHIP3 varchar(50) default NULL, ST_GTHAN4 varchar(50) default NULL, ST_LTHAN4 varchar(50) default NULL, ST_SHIP4 varchar(50) default NULL, ST_GTHAN5 varchar(50) default NULL, ST_LTHAN5 varchar(50) default NULL, ST_SHIP5 varchar(50) default NULL, ST_GTHAN6 varchar(50) default NULL, ST_LTHAN6 varchar(50) default NULL, ST_SHIP6 varchar(50) default NULL, ST_GTHAN7 varchar(50) default NULL, ST_LTHAN7 varchar(50) default NULL, ST_SHIP7 varchar(50) default NULL, ST_GTHAN8 varchar(50) default NULL, ST_LTHAN8 varchar(50) default NULL, ST_SHIP8 varchar(50) default NULL, INC_FILENAME varchar(50) default NULL, NOTICE blob, order_type varchar(50) default NULL, local_country varchar(255) default NULL)';
		$create_tables['cart_tax'] = 'CREATE TABLE cart_tax ( state char(255) default NULL, rate char(7) default NULL)';
		$create_tables['cart_vat'] = 'CREATE TABLE cart_vat ( country char(25) default NULL, rate char(7) default NULL)';
		$create_tables['cart_worldpay'] = 'CREATE TABLE cart_worldpay ( WP_INSTALL_ID char(255) default NULL, WP_LATER char(255) default NULL, WP_LATER2 char(255) default NULL, WP_LATER3 char(255) default NULL)';
		$create_tables['faq_category'] = 'CREATE TABLE faq_category ( prikey int(11) NOT NULL auto_increment primary key, CAT_NAME char(30) default NULL)';
		$create_tables['faq_content'] = 'CREATE TABLE faq_content ( prikey int(11) NOT NULL auto_increment primary key, SORT_NUM varchar(30) default NULL, CAT_NAME varchar(30) default NULL, FAQ_QUESTION blob, FAQ_ANSWER blob)';
		$create_tables['form_fields'] = 'CREATE TABLE form_fields ( prikey int(11) NOT NULL auto_increment primary key, dbname varchar(255) default NULL, title varchar(255) default NULL, field_type varchar(100) default NULL, field_id varchar(100) default NULL, form_id varchar(255) default NULL, sort_order int(10) default NULL, required varchar(50) default NULL, width varchar(50) default NULL, style blob, choices blob, checked varchar(255) default NULL, notes blob)';
		$create_tables['form_properties'] = 'CREATE TABLE form_properties ( prikey int(11) NOT NULL auto_increment primary key, form_name varchar(255) default NULL, date_created int(25) default NULL, form_id varchar(100) default NULL, form_filename varchar(255) default NULL, style blob)';
		$create_tables['form_submissions'] = 'CREATE TABLE form_submissions ( prikey int(50) NOT NULL auto_increment primary key, db_table_key varchar(255) default NULL, db_table varchar(255) default NULL, form_name varchar(255) default NULL, referrer varchar(255) default NULL, form_details blob, ip_address varchar(255) default NULL, date varchar(255) default NULL, time varchar(255) default NULL)';
		$create_tables['ip_bans'] = 'CREATE TABLE ip_bans ( prikey int(50) NOT NULL auto_increment primary key, ip_address varchar(255) default NULL, date varchar(255) default NULL, time varchar(255) default NULL, ban_expires varchar(255) NOT NULL default \'\', reason varchar(255) default NULL)';
		$create_tables['login_attempts'] = 'CREATE TABLE login_attempts ( PRIKEY int(11) NOT NULL auto_increment primary key, ip_address char(50) default NULL, date char(50) default NULL, time char(25) default NULL, username char(50) default NULL, password char(50) default NULL)';
		$create_tables['login_bans'] = 'CREATE TABLE login_bans ( PRIKEY int(11) NOT NULL auto_increment primary key, ip_address char(50) default NULL, date char(50) default NULL, time char(25) default NULL)';
		$create_tables['login_history'] = 'CREATE TABLE login_history ( prikey int(11) NOT NULL auto_increment primary key, ip_address varchar(50) default NULL, username varchar(255) default NULL, date varchar(50) default NULL, time varchar(25) default NULL)';
		$create_tables['photo_album'] = 'CREATE TABLE photo_album ( prikey int(11) NOT NULL auto_increment primary key, album_name char(255) default NULL)';
		$create_tables['photo_album_images'] = 'CREATE TABLE photo_album_images ( prikey int(11) NOT NULL auto_increment primary key, album_id int(64) default NULL, image_order int(64) default NULL, image_name varchar(255) default NULL, caption blob)';
		$create_tables['promo_boxes'] = 'CREATE TABLE promo_boxes ( PRIKEY int(11) NOT NULL auto_increment primary key, BOX varchar(255) default NULL, CONTENT varchar(255) default NULL, NUM_DISPLAY varchar(255) default NULL, DISP_TITLE varchar(255) default NULL, DISP_CONTENT varchar(255) default NULL, DISP_DATE varchar(255) default NULL, DISP_MORE varchar(255) default NULL, FILE varchar(255) default NULL, SETTINGS varchar(255) default NULL, FUTURE1 varchar(255) default NULL, content_type varchar(50) default NULL, content_src varchar(255) default NULL, style blob)';
		$create_tables['qty_discounts'] = 'CREATE TABLE qty_discounts ( sku varchar(255) default NULL, disc_type varchar(255) default NULL, required_qty varchar(255) default NULL, min_qty blob, max_qty blob, disc blob)';
		$create_tables['search_contents'] = 'CREATE TABLE search_contents ( prikey int(11) NOT NULL auto_increment primary key, page_name varchar(255) default NULL, include_in_search varchar(255) default NULL, page_contents blob)';
		$create_tables['search_core'] = 'CREATE TABLE search_core ( prikey int(11) NOT NULL auto_increment primary key, template varchar(255) default NULL, results_per_page varchar(255) default NULL, show_search_type varchar(255) default NULL, search_button_text varchar(255) default NULL, custom_button varchar(255) default NULL, display_percent varchar(255) default NULL, percent_text varchar(255) default NULL, display_hits varchar(255) default NULL, hits_text varchar(255) default NULL, allow_template_search varchar(255) default NULL, min_word_chars varchar(255) default NULL, style1 varchar(255) default NULL, style2 varchar(255) default NULL, style3 varchar(255) default NULL, style4 varchar(255) default NULL, search_field_label varchar(75) default NULL, display_search_within_results varchar(5) default NULL, display_match_exact_phrase varchar(5) default NULL, link_color varchar(6) default NULL, link_hover varchar(6) default NULL, stats varchar(10) default NULL, display_number varchar(5) default NULL)';
		$create_tables['search_stats'] = 'CREATE TABLE search_stats ( search_count varchar(30) default NULL, search_phrase varchar(100) default NULL, month varchar(40) default NULL, found char(3) default NULL)';
		$create_tables['sec_codes'] = 'CREATE TABLE sec_codes ( PriKey int(11) NOT NULL auto_increment primary key, security_code char(15) default NULL)';
		$create_tables['sec_users'] = 'CREATE TABLE sec_users ( PRIKEY int(11) NOT NULL auto_increment primary key, OWNER_NAME varchar(150) default NULL, OWNER_EMAIL varchar(150) default NULL, USERNAME varchar(150) default NULL, PASSWORD varchar(150) default NULL, REDIRECT_PAGE varchar(150) default NULL, BFIRSTNAME varchar(150) default NULL, BLASTNAME varchar(150) default NULL, BCOMPANY varchar(150) default NULL, BADDRESS1 varchar(150) default NULL, BADDRESS2 varchar(150) default NULL, BCITY varchar(150) default NULL, BSTATE varchar(150) default NULL, BCOUNTRY varchar(150) default NULL, BZIPCODE varchar(150) default NULL, BPHONE_COUNTRYCODE varchar(150) default NULL, BPHONE_AREACODE varchar(150) default NULL, BPHONE_PREFIX varchar(150) default NULL, BPHONE_SUFFIX varchar(150) default NULL, BEMAILADDRESS varchar(150) default NULL, SFIRSTNAME varchar(150) default NULL, SLASTNAME varchar(150) default NULL, SCOMPANY varchar(150) default NULL, SADDRESS1 varchar(150) default NULL, SADDRESS2 varchar(150) default NULL, SCITY varchar(150) default NULL, SSTATE varchar(150) default NULL, SCOUNTRY varchar(150) default NULL, SZIPCODE varchar(150) default NULL, SPHONE_COUNTRYCODE varchar(150) default NULL, SPHONE_AREACODE varchar(150) default NULL, SPHONE_PREFIX varchar(150) default NULL, SPHONE_SUFFIX varchar(150) default NULL, GROUPS blob, EXPIRATION_DATE date default NULL, MD5CODE varchar(255) default NULL)';
		$create_tables['simple_chat'] = 'CREATE TABLE simple_chat ( prikey int(50) NOT NULL auto_increment primary key, chat_name varchar(255) default NULL, message blob, date varchar(255) default NULL, time int(60) default NULL, ip_address varchar(255) default NULL)';
		$create_tables['site_backup'] = 'CREATE TABLE site_backup ( PRIKEY int(11) NOT NULL auto_increment primary key, BAK_ID varchar(50) default NULL, BAK_DATE varchar(50) default NULL, BAK_TIME varchar(25) default NULL, BAK_TITLE varchar(255) default NULL, BAK_NOTES blob, BAK_FILE varchar(255) default NULL, BAK_TYPE varchar(255) default NULL, BAK_DIRS varchar(255) default NULL, BAK_TABLES varchar(255) default NULL, BAK_TEMPLATES varchar(255) default NULL, BAK_FILES varchar(255) default NULL, BAK_PAGES varchar(255) default NULL, BAK_LIST blob, CUSTOM1 varchar(255) default NULL, CUSTOM2 varchar(255) default NULL, CUSTOM3 blob, FUTURE1 varchar(255) default NULL, FUTURE2 varchar(255) default NULL, FUTURE3 blob)';
		$create_tables['site_pages'] = 'CREATE TABLE site_pages ( prikey int(50) NOT NULL auto_increment primary key, page_name varchar(255) NOT NULL default \'\', url_name varchar(255) default NULL, type varchar(75) default NULL, custom_menu blob, sub_pages blob, sub_page_of varchar(255) default NULL, password blob, main_menu int(25) default NULL, link blob, username varchar(35) default NULL, splash char(1) default NULL, bgcolor blob, title varchar(255) default NULL, description blob, template varchar(100) default NULL, content blob, content_regen blob)';
		$create_tables['site_specs'] = 'CREATE TABLE site_specs ( prikey int(50) NOT NULL auto_increment primary key, df_company varchar(255) default NULL, df_address1 varchar(255) default NULL, df_address2 varchar(255) default NULL, df_city varchar(100) default NULL, df_state varchar(100) default NULL, df_zip varchar(25) default NULL, df_country varchar(50) default NULL, df_phone varchar(50) default NULL, df_email varchar(255) default NULL, df_domain varchar(255) default NULL, df_page varchar(50) default NULL, df_logo varchar(255) default NULL, df_lang varchar(50) default NULL, news_cat varchar(10) default NULL, promo_cat varchar(10) default NULL, copyright blob, df_misc1 blob, df_misc2 blob, df_hdrtxt varchar(255) default NULL, df_slogan varchar(255) default NULL, dev_mode varchar(255) default NULL, startpage varchar(255) default NULL, df_fax varchar(50) default NULL)';
		$create_tables['smt_userdata'] = 'CREATE TABLE smt_userdata ( prikey int(10) NOT NULL auto_increment primary key, plugin varchar(75) default NULL, fieldname varchar(255) default NULL, data blob)';
		$create_tables['smt_userimages'] = 'CREATE TABLE smt_userimages ( prikey int(11) NOT NULL auto_increment primary key, template_folder varchar(255) default NULL, layout_file varchar(255) default NULL, orig_image varchar(255) default NULL, user_image varchar(255) default NULL, page varchar(255) default NULL)';
		$create_tables['stats_browser'] = 'CREATE TABLE stats_browser ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, Browser char(255) default NULL, Hits int(25) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['stats_browser_archive'] = 'CREATE TABLE stats_browser_archive ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, Browser char(255) default NULL, Hits int(25) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['stats_byday'] = 'CREATE TABLE stats_byday ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, Day char(25) default NULL, Hits int(25) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['stats_byday_archive'] = 'CREATE TABLE stats_byday_archive ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, Day char(25) default NULL, Hits int(25) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['stats_byhour'] = 'CREATE TABLE stats_byhour ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, Hour char(25) default NULL, Hits int(25) default NULL, SESSION char(255) default NULL, Real_Date date default NULL, Min_Users int(8) default NULL, Max_Users int(8) default NULL, Avg_Users float default NULL)';
		$create_tables['stats_byhour_archive'] = 'CREATE TABLE stats_byhour_archive ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, Hour char(25) default NULL, Hits int(25) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['stats_refer'] = 'CREATE TABLE stats_refer ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, Refer char(255) default NULL, Hits int(25) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['stats_refer_archive'] = 'CREATE TABLE stats_refer_archive ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, Refer char(255) default NULL, Hits int(25) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['stats_top25'] = 'CREATE TABLE stats_top25 ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, Page char(25) default NULL, Hits int(25) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['stats_top25_archive'] = 'CREATE TABLE stats_top25_archive ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, Page char(25) default NULL, Hits int(25) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['stats_unique'] = 'CREATE TABLE stats_unique ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, IP char(25) default NULL, Hour char(25) default NULL, Hits int(25) default NULL, Browser char(100) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['stats_unique_archive'] = 'CREATE TABLE stats_unique_archive ( PriKey int(11) NOT NULL auto_increment primary key, Month char(25) default NULL, Year int(4) default NULL, IP char(25) default NULL, Hour char(25) default NULL, Hits int(25) default NULL, Browser char(100) default NULL, SESSION char(255) default NULL, Real_Date date default NULL)';
		$create_tables['system_hook_attachments'] = 'CREATE TABLE system_hook_attachments ( PRIKEY int(11) NOT NULL auto_increment primary key, PLUGIN_FOLDER varchar(255) default NULL, HOOK_TYPE varchar(255) default NULL, HOOK_ID varchar(255) default NULL, HOOK_FILE varchar(255) default NULL, MOD_FILE varchar(255) default NULL, HOOK_DATA blob, LAST_UPDATED varchar(30) default NULL)';
		$create_tables['system_plugins'] = 'CREATE TABLE system_plugins ( PRIKEY int(11) NOT NULL auto_increment primary key, PLUGIN_FOLDER varchar(255) default NULL, TITLE varchar(255) default NULL, VERSION varchar(255) default NULL, DESCRIPTION varchar(255) default NULL, AUTHOR varchar(255) default NULL, HOMEPAGE varchar(255) default NULL, ICON varchar(255) default NULL, OPTIONS_LINK varchar(255) default NULL, MISC blob, LAST_UPDATED varchar(30) default NULL, changelog blob, release_date varchar(50) default NULL)';
		$create_tables['unsubscribe'] = 'CREATE TABLE unsubscribe ( PRIKEY int(11) NOT NULL auto_increment primary key, UNSUB_EMAIL_ADDR char(255) default NULL, UNSUB_DATE date default NULL)';
		$create_tables['user_access_rights'] = 'CREATE TABLE user_access_rights ( PRIKEY int(11) NOT NULL auto_increment primary key, LOGIN_KEY int(25) default NULL, ACCESS_STRING blob, PICTURE blob, FUTURE2 blob)';
		$create_tables['UDT_CONTENT_SEARCH_REPLACE'] = 'CREATE TABLE UDT_CONTENT_SEARCH_REPLACE ( PRIKEY int(11) NOT NULL auto_increment primary key, SEARCH_FOR varchar(150) default NULL, REPLACE_WITH blob, AUTO_IMAGE varchar(100) default NULL, AUTO_SECURITY_AUTH varchar(255) default NULL)';

		mysql_query($create_tables[$tbl_name]);
		if(table_exists($tbl_name)){
			return true;
		} else {
			return false;	
		}
	} else {
		return true;
	}
}
?>